# Generated by Django 5.2.17 on 2026-09-05 16:43

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                            ("portal", "Portal"),
                            ("outreach", "Outreach"),
                        ],
                        max_length=10,
                    ),
                ),
                ("applied_on", models.DateField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screen", "Recruiter screen"),
                            ("oa", "Online assessment"),
                            ("tech", "Technical round"),
                            ("final", "Final round"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("ghosted", "Ghosted (manually marked)"),
                        ],
                        default="applied",
                        max_length=10,
                    ),
                ),
                ("last_update", models.DateField()),
                ("last_email_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("company_domain", models.CharField(blank=True, max_length=200)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_update"],
                "unique_together": {("company", "role")},
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=4, unique=True)),
                ("label", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("build", "Build"),
                            ("learn", "Learn"),
                            ("apply", "Apply"),
                            ("sharpen", "Sharpen"),
                            ("flex", "Flex"),
                        ],
                        max_length=10,
                    ),
                ),
                ("typical_minutes_min", models.PositiveSmallIntegerField()),
                ("typical_minutes_max", models.PositiveSmallIntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BlockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("active_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("what", models.TextField(blank=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.block",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["daily_log", "block__code"],
            },
        ),
        migrations.CreateModel(
            name="ActivitySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("app", models.CharField(max_length=200)),
                ("window_title", models.CharField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("build", "Build"),
                            ("learn", "Learn"),
                            ("apply", "Apply"),
                            ("sharpen", "Sharpen"),
                            ("flex", "Flex"),
                            ("idle", "Idle"),
                            ("distraction", "Distraction"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_samples",
                        to="core.blockentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CertDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cert_code", models.CharField(max_length=20)),
                ("domain_no", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("weight_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight_is_approximate", models.BooleanField(default=True)),
                (
                    "mastery_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_studied", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["cert_code", "domain_no"],
                "unique_together": {("cert_code", "domain_no")},
            },
        ),
        migrations.CreateModel(
            name="Countdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=200)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("editable", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["target_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=100)),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("exam_cert", "Exam certification"),
                            ("certificate", "Certificate of completion"),
                            ("none", "No credential"),
                        ],
                        max_length=12,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField(unique=True)),
                ("deep_work_minutes", models.PositiveIntegerField(default=0)),
                (
                    "energy",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("steps_after_10", models.PositiveIntegerField(default=0)),
                ("gym", models.BooleanField(default=False)),
                ("last_caffeine_at", models.TimeField(blank=True, null=True)),
                ("mood", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
            },
        ),
        migrations.AddField(
            model_name="blockentry",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_entries",
                to="core.dailylog",
            ),
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gmail_message_id", models.CharField(max_length=200, unique=True)),
                ("received_at", models.DateTimeField()),
                ("from_address", models.CharField(max_length=200)),
                ("subject", models.CharField(blank=True, max_length=500)),
                (
                    "classified_as",
                    models.CharField(
                        choices=[
                            ("rejection", "Rejection"),
                            ("interview_invite", "Interview invite"),
                            ("oa_link", "OA link"),
                            ("acknowledgement", "Acknowledgement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("matched", models.BooleanField(default=False)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_events",
                        to="core.application",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("week_no", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("cert", "Certification"),
                            ("content", "Content"),
                            ("career", "Career"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("doing", "Doing"),
                            ("done", "Done"),
                            ("dropped", "Dropped"),
                        ],
                        default="todo",
                        max_length=10,
                    ),
                ),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("evidence_url", models.URLField(blank=True)),
                ("post_angle", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="ContentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("blog", "Blog"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField(blank=True)),
                ("posted_on", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("reactions", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_posts",
                        to="core.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_on"],
            },
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("phase_no", models.PositiveSmallIntegerField(unique=True)),
                ("theme", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["phase_no"],
            },
        ),
        migrations.AddField(
            model_name="milestone",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestones",
                to="core.phase",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("one_liner", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("shipped", "Shipped"),
                            ("parked", "Parked"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                ("repo_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                (
                    "tech",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("publish_gate", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="milestone",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="core.project",
            ),
        ),
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField(unique=True)),
                ("went_well", models.TextField(blank=True)),
                ("blocked_by", models.TextField(blank=True)),
                ("one_thing_tomorrow", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "target",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField(unique=True)),
                ("bed_at", models.DateTimeField(blank=True, null=True)),
                ("wake_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("shortcut", "iPhone Shortcut"),
                            ("estimate", "Estimate"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField()),
                ("topic", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("minutes", models.PositiveIntegerField()),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "cert_domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="core.certdomain",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="core.course",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_no", models.PositiveSmallIntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("theme", models.CharField(blank=True, max_length=200)),
                ("build_focus", models.CharField(blank=True, max_length=200)),
                ("learn_focus", models.CharField(blank=True, max_length=200)),
                ("sharpen_focus", models.CharField(blank=True, max_length=200)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="core.phase",
                    ),
                ),
            ],
            options={
                "ordering": ["week_no"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="blockentry",
            unique_together={("daily_log", "block")},
        ),
        migrations.CreateModel(
            name="LossPostmortem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round_reached", models.CharField(blank=True, max_length=20)),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("take_home", "Take-home / OA"),
                            ("system_design", "System design"),
                            ("dsa", "DSA / algorithms"),
                            ("behavioral", "Behavioral"),
                            ("domain_knowledge", "Domain knowledge"),
                            ("communication", "Communication"),
                            ("culture_fit", "Culture fit"),
                            ("comp_mismatch", "Compensation mismatch"),
                            ("ghosted_by_them", "They went silent"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("what_happened", models.TextField(blank=True)),
                ("logged_on", models.DateField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmortems",
                        to="core.application",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_on"],
                "unique_together": {("application", "round_reached")},
            },
        ),
        migrations.CreateModel(
            name="PracticeTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cert_code", models.CharField(max_length=20)),
                ("taken_on", models.DateField()),
                ("score", models.PositiveIntegerField()),
                ("max_score", models.PositiveIntegerField(default=1000)),
                ("per_domain", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["taken_on"],
                "unique_together": {("cert_code", "taken_on")},
            },
        ),
    ]
