# Generated by Django 5.2.17 on 2026-09-06 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_program"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notion_page_id", models.CharField(max_length=64, unique=True)),
                ("title", models.TextField()),
                ("status", models.CharField(blank=True, default="", max_length=100)),
                ("category", models.CharField(blank=True, max_length=200, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notion_last_edited", models.DateTimeField()),
                ("synced_at", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-notion_last_edited"],
            },
        ),
    ]
