# Generated by Django 5.2.17 on 2026-09-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_correct_course_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notiontask",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="build_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="learn_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="week",
            name="sharpen_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
