# Generated by Django 5.2.17 on 2026-09-13 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_shift_program_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("linkedin_easy_apply", "LinkedIn Easy Apply"),
                    ("cutshort", "Cutshort"),
                    ("careers_page", "Company careers page"),
                    ("naukri", "Naukri"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="heard_back",
            field=models.CharField(
                choices=[("pending", "Pending"), ("yes", "Yes"), ("no", "No")],
                default="pending",
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="LinkedInSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_date", models.DateField(unique=True)),
                ("post_impressions", models.PositiveIntegerField()),
                ("post_likes", models.PositiveIntegerField()),
                ("connections", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
            },
        ),
    ]
