# Generated by Django 5.2.17 on 2026-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_seed_job_search_2026_09_13"),
    ]

    operations = [
        migrations.AddField(
            model_name="todayselection",
            name="notion_prior_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
